# Generated by Django 6.0.6 on 2026-06-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha']},
        ),
    ]
